# coding:utf-8
# DO NOT EDIT THIS FILE
# make a copy to your working directory
# and edit that file

dir = "."
download_ori = False
download_thread_cnt = 5
scan_thread_cnt = 1
proxy = None
log_path = "eh.log"
log_verbose = 2
daemon = False
fast_scan = False
rpc_interface = 'localhost'
rpc_port = None
rpc_secret = None
